tap "ferdium/ferdium"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "thoughtbot/formulae"
brew "apr-util"
brew "autoconf"
brew "automake"
brew "python@3.11"
brew "awscli"
brew "awslogs"
brew "bluetoothconnector"
brew "glib"
brew "python@3.9"
brew "cairo"
brew "cmake"
brew "libidn2"
brew "openldap"
brew "curl"
brew "libtool"
brew "freetds"
brew "libpq"
brew "php"
brew "composer"
brew "libevent"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libass"
brew "srt"
brew "tesseract"
brew "ffmpeg"
brew "ghq"
brew "gibo"
brew "git"
brew "go"
brew "gobject-introspection"
brew "grep"
brew "guile"
brew "htop"
brew "hub"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "mas"
brew "nghttp2"
brew "nkf"
brew "node"
brew "p7zip"
brew "picocom"
brew "pipx"
brew "postgresql@14"
brew "privoxy", restart_service: true
brew "pyenv"
brew "python@3.10"
brew "tcl-tk"
brew "python@3.8"
brew "ruby-build"
brew "rbenv"
brew "rename"
brew "switchaudio-osx"
brew "tfenv"
brew "tflint"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tor", restart_service: true
brew "tree"
brew "wget"
brew "yarn"
brew "zlib"
brew "zsh"
brew "heroku/brew/heroku"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "abyssoft-teleport"
cask "alfred"
cask "appcleaner"
cask "authy"
cask "bartender"
cask "bettertouchtool"
cask "chromedriver"
cask "cron"
cask "deepl"
cask "discord"
cask "docker"
cask "dropbox"
cask "ferdium"
cask "font-ricty-diminished"
cask "gimp"
cask "google-cloud-sdk"
cask "grammarly-desktop"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keepingyouawake"
cask "notion"
cask "pritunl"
cask "qmk-toolbox"
cask "synology-drive"
cask "ticktick"
cask "vagrant"
cask "xquartz"
cask "zoom"
mas "com.alice.mac.GetPlainText", id: 508368068
mas "CotEditor", id: 1024640650
mas "Day One", id: 1055511498
mas "Evernote", id: 406056744
mas "GIPHY CAPTURE", id: 668208984
mas "GoodNotes", id: 1444383602
mas "GrandPerspective", id: 1111570163
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Mini Your Photos", id: 674564410
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "PopClip", id: 445189367
mas "Skitch", id: 425955336
mas "StuffIt Expander", id: 405580712
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
