tap "ferdium/ferdium"
tap "heroku/brew"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "sanemat/font"
tap "thoughtbot/formulae"
brew "zstd"
brew "libtiff"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "aria2"
brew "autoconf"
brew "automake"
brew "icu4c@78"
brew "awscli"
brew "awslogs"
brew "bluetoothconnector"
brew "glib"
brew "cairo"
brew "pycparser"
brew "cffi"
brew "cmake"
brew "libtool"
brew "freetds"
brew "libavif"
brew "gd"
brew "libpq", link: true
brew "libzip"
brew "php"
brew "composer"
brew "direnv"
brew "docutils"
brew "duti"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "openjpeg"
brew "leptonica"
brew "libass"
brew "libmicrohttpd"
brew "librist"
brew "pango"
brew "srt"
brew "tesseract"
brew "ffmpeg"
brew "fnm"
brew "fontforge"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "ghq"
brew "gibo"
brew "git"
brew "go"
brew "gobject-introspection"
brew "grep"
brew "guile"
brew "htop"
brew "hub"
brew "shared-mime-info"
brew "libheif"
brew "python@3.12"
brew "imagemagick"
brew "jq"
brew "keyring"
brew "llvm"
brew "mas"
brew "minimal-racket"
brew "mysql"
brew "nghttp2"
brew "nkf"
brew "node"
brew "p7zip"
brew "pandoc"
brew "picocom"
brew "pipx"
brew "poetry"
brew "privoxy", restart_service: :changed
brew "protobuf"
brew "pyenv"
brew "python@3.10"
brew "python@3.11"
brew "python@3.9"
brew "rakudo"
brew "ruby-build"
brew "rbenv"
brew "rename"
brew "rust"
brew "shellcheck"
brew "speedtest-cli"
brew "starship"
brew "swi-prolog"
brew "switchaudio-osx"
brew "tcl-tk"
brew "telnet"
brew "tfenv"
brew "tflint"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tor", restart_service: :changed
brew "tree"
brew "unar"
brew "uv"
brew "virtualenv"
brew "wget"
brew "yarn"
brew "zoxide"
brew "zsh"
brew "heroku/brew/heroku"
brew "qmk/qmk/qmk"
brew "sanemat/font/ricty"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "alfred"
cask "anki"
cask "appcleaner"
cask "bartender"
cask "bettertouchtool"
cask "citrix-workspace"
cask "claude"
cask "cleanmymac"
cask "cleanshot"
cask "codex"
cask "cursor"
cask "deepl"
cask "discord"
cask "docker-desktop"
cask "dropbox"
cask "ferdium"
cask "firefox"
cask "font-hack-nerd-font"
cask "font-hackgen"
cask "gcloud-cli"
cask "gimp"
cask "google-chrome"
cask "google-drive"
cask "grammarly-desktop"
cask "hammerspoon"
cask "imageoptim"
cask "istat-menus"
cask "jetbrains-toolbox"
cask "logi-options+"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "mysqlworkbench"
cask "notion"
cask "notion-calendar"
cask "pgadmin4"
cask "pritunl"
cask "qmk-toolbox"
cask "sequel-ace"
cask "synology-drive"
cask "tempbox"
cask "ticktick"
cask "timemachineeditor"
cask "visual-studio-code"
cask "wezterm"
cask "wireshark-app"
cask "xquartz"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "CotEditor", id: 1024640650
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "Goodnotes", id: 1444383602
mas "GrandPerspective", id: 1111570163
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "MARKETSPEED", id: 946680495
mas "NAS Navigator2", id: 450664466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "PopClip", id: 445189367
mas "Pure Paste", id: 1611378436
mas "StuffIt Expander", id: 405580712
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
vscode "anysphere.cursorpyright"
vscode "anysphere.remote-containers"
vscode "anysphere.remote-ssh"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "george-alisson.html-preview-vscode"
vscode "github.vscode-github-actions"
vscode "hashicorp.terraform"
vscode "humao.rest-client"
vscode "jdinhlife.gruvbox"
vscode "mechatroner.rainbow-csv"
vscode "mongodb.mongodb-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "njpwerner.autodocstring"
vscode "openai.chatgpt"
vscode "pranaygp.vscode-css-peek"
vscode "vitest.explorer"
