tap "ferdium/ferdium"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/services"
tap "lencx/chatgpt", "https://github.com/lencx/ChatGPT.git"
tap "sanemat/font"
tap "thoughtbot/formulae"
brew "zstd"
brew "libtiff"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "aria2"
brew "autoconf"
brew "automake"
brew "pycparser"
brew "cffi"
brew "python@3.11"
brew "awscli"
brew "python@3.12"
brew "awslogs"
brew "bluetoothconnector"
brew "glib"
brew "cairo"
brew "cmake"
brew "libtool"
brew "freetds"
brew "libavif"
brew "gd"
brew "libzip"
brew "php"
brew "composer"
brew "direnv"
brew "docutils"
brew "duti"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "openjpeg"
brew "leptonica"
brew "libass"
brew "libmicrohttpd"
brew "librist"
brew "pango"
brew "srt"
brew "tesseract"
brew "ffmpeg"
brew "fontforge"
brew "ghostscript"
brew "ghq"
brew "gibo"
brew "git"
brew "go"
brew "gobject-introspection"
brew "grep"
brew "guile"
brew "htop"
brew "hub"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "keyring"
brew "llvm"
brew "mas"
brew "mysql"
brew "nghttp2"
brew "nkf"
brew "node"
brew "nvm"
brew "p7zip"
brew "pandoc"
brew "picocom"
brew "pipx"
brew "poetry"
brew "postgresql@14"
brew "privoxy", restart_service: true
brew "protobuf"
brew "pyenv"
brew "python@3.10"
brew "python@3.9"
brew "ruby-build"
brew "rbenv"
brew "rename"
brew "rust"
brew "speedtest-cli"
brew "switchaudio-osx"
brew "tcl-tk"
brew "telnet"
brew "tfenv"
brew "tflint"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tor", restart_service: true
brew "tree"
brew "unar"
brew "virtualenv"
brew "wget"
brew "yarn"
brew "zsh"
brew "heroku/brew/heroku"
brew "sanemat/font/ricty"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "alfred"
cask "appcleaner"
cask "bartender"
cask "bettertouchtool"
cask "chromedriver"
cask "citrix-workspace"
cask "cleanmymac"
cask "cleanshot"
cask "cursor"
cask "deepl"
cask "discord"
cask "docker"
cask "dropbox"
cask "ferdium"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "grammarly-desktop"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "logi-options+"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "notion"
cask "notion-calendar"
cask "obsidian"
cask "pritunl"
cask "pushplaylabs-sidekick"
cask "qmk-toolbox"
cask "sequel-ace"
cask "skype"
cask "synology-drive"
cask "tempbox"
cask "ticktick"
cask "timemachineeditor"
cask "visual-studio-code"
cask "xquartz"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "CotEditor", id: 1024640650
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "Goodnotes", id: 1444383602
mas "GrandPerspective", id: 1111570163
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "NAS Navigator2", id: 450664466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "PopClip", id: 445189367
mas "Pure Paste", id: 1611378436
mas "StuffIt Expander", id: 405580712
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
vscode "blindtiger.masm"
vscode "george-alisson.html-preview-vscode"
vscode "humao.rest-client"
vscode "mohd-akram.vscode-html-format"
vscode "mongodb.mongodb-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "pranaygp.vscode-css-peek"
vscode "ransh.ransh"
